// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQO5GlVWQ8AqaO8LRWsz67eHFgUq5GJeI',
    appId: '1:154422495760:web:97b57a903b427a50bf9895',
    messagingSenderId: '154422495760',
    projectId: 'parkmate-flutter',
    authDomain: 'parkmate-flutter.firebaseapp.com',
    storageBucket: 'parkmate-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdXxgRdGPlaNtJzgQwAiqIX94VmqW5O_M',
    appId: '1:154422495760:android:3d5c46bf2861d31cbf9895',
    messagingSenderId: '154422495760',
    projectId: 'parkmate-flutter',
    storageBucket: 'parkmate-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0DADBwoTB_Y1sf-OkzJGhtgupQ-___c',
    appId: '1:154422495760:ios:3fa1e90c659c2211bf9895',
    messagingSenderId: '154422495760',
    projectId: 'parkmate-flutter',
    storageBucket: 'parkmate-flutter.appspot.com',
    iosBundleId: 'com.example.parkmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0DADBwoTB_Y1sf-OkzJGhtgupQ-___c',
    appId: '1:154422495760:ios:3fa1e90c659c2211bf9895',
    messagingSenderId: '154422495760',
    projectId: 'parkmate-flutter',
    storageBucket: 'parkmate-flutter.appspot.com',
    iosBundleId: 'com.example.parkmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQO5GlVWQ8AqaO8LRWsz67eHFgUq5GJeI',
    appId: '1:154422495760:web:d745ef9591f7718cbf9895',
    messagingSenderId: '154422495760',
    projectId: 'parkmate-flutter',
    authDomain: 'parkmate-flutter.firebaseapp.com',
    storageBucket: 'parkmate-flutter.appspot.com',
  );

}